---

dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: "test01-docker-centos7"
    image: 'jrei/systemd-centos:7'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "test01-docker-centos8"
    image: 'jrei/systemd-centos:7'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "test01-docker-debian9"
    image: 'jrei/systemd-debian:latest'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "test01-docker-debian10"
    image: 'jrei/systemd-debian:latest'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "test01-docker-ubuntu18"
    image: 'jrei/systemd-ubuntu:18.04'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  - name: "test01-docker-ubuntu20"
    image: 'jrei/systemd-ubuntu:20.04'
    privileged: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
provisioner:
  name: 'ansible'
  inventory:
    group_vars:
      all: {}
    host_vars: {}
scenario:
  name: 'default'
verifier:
  name: 'testinfra'
  additional_files_or_dirs:
    - '../../tests'
  options:
    sudo: True
